config/routes.rb
Rails.application.routes.draw do
  # get 'pages/about'
  # get 'pages/contact'
  root to: 'pages#home'
  
  get "about", to: "pages#about"
  get "contact", to: "pages#contact"
  get "restaurants", to: "restaurants#index"
  get "restaurants/:id", to: "restaurants#show", as:"restaurant"
  post "restaurants", to: "restaurants#create"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def home
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  
  RESTAURANTS = {
    1 => { name: "piba", address: "libertador 600", category: "pinchos"},
    2 => { name: "siga la vaca", address: "parana 945", category: "parrilla"},
    3 => { name: "kansas", address: "córdoba 900", category: "american food"},
    4 => { name: "la farola", address: "santa fe 456", category: "pastas"}
  }

  def index
    @restaurants = if params[:food_type].present?
      RESTAURANTS.select do |id, restaurant|
        restaurant[:category] == params[:food_type]
      end
    else
      RESTAURANTS
    end
  end

  def create
    render plain: "crearía el restaurant #{params[:name]} en la dirección #{params[:address]}"
  end

  def show
    @restaurant = RESTAURANTS[params[:id].to_i]    
  end
  
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Thespoon</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <footer>
      <%= link_to "Nosotros", about_path %>
      <%= link_to "Contacto", contact_path %>
      <p>Now is <%= Time.now %><p>
    </footer>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Nosotros</h1>
<p>Historia de nuestro equipo</p>

app/views/pages/contact.html.erb
<h1>Contactos</h1>

app/views/pages/home.html.erb
<h1>Welcome</h1>

<form action="/restaurants" method="get">
  <input type="text" name="food_type" placeholder="What kind of food?">
  <input type="submit">
</form>

<form action="/restaurants" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type="text" name="name" placeholder="Name">
  <input type="text" name="address" placeholder="Address">
  <input type="submit">
</form>

app/views/restaurants/index.html.erb
<h1>Nuestros Restaurants</h1>

<h2>Categorías</h2>

<% categories = %w[Rápida Indian Mexicana] %>

<ul>
  <% categories.each do |category| %>
  <li><%= category %></li>  
  <% end %>
</ul>

<h2>Restaurants</h2>

<ul>
  <% @restaurants.each do |id, restaurant| %>
    <li>
      <%= link_to restaurant[:name], restaurant_path(id) %>
    </li>
  <% end %>
</ul>

app/views/restaurants/show.html.erb
<h1>El mejor Restaurant</h1>
<h2><%= @restaurant[:name] %></h2>

<%= link_to "Volver al listado", restaurants_path %>